// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/internal/domain/entities/Event.proto

package entities

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Period int32

const (
	Period_ALL   Period = 0
	Period_DAY   Period = 1
	Period_WEEK  Period = 2
	Period_MONTH Period = 3
)

var Period_name = map[int32]string{
	0: "ALL",
	1: "DAY",
	2: "WEEK",
	3: "MONTH",
}

var Period_value = map[string]int32{
	"ALL":   0,
	"DAY":   1,
	"WEEK":  2,
	"MONTH": 3,
}

func (x Period) String() string {
	return proto.EnumName(Period_name, int32(x))
}

func (Period) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_542299000a857ba7, []int{0}
}

type Event struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId              string               `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	Duration             *timestamp.Timestamp `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	NotifyTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=notify_time,json=notifyTime,proto3" json:"notify_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_542299000a857ba7, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Event) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Event) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Event) GetDuration() *timestamp.Timestamp {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Event) GetNotifyTime() *timestamp.Timestamp {
	if m != nil {
		return m.NotifyTime
	}
	return nil
}

type EventCreateRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventCreateRequest) Reset()         { *m = EventCreateRequest{} }
func (m *EventCreateRequest) String() string { return proto.CompactTextString(m) }
func (*EventCreateRequest) ProtoMessage()    {}
func (*EventCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_542299000a857ba7, []int{1}
}

func (m *EventCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventCreateRequest.Unmarshal(m, b)
}
func (m *EventCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventCreateRequest.Marshal(b, m, deterministic)
}
func (m *EventCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventCreateRequest.Merge(m, src)
}
func (m *EventCreateRequest) XXX_Size() int {
	return xxx_messageInfo_EventCreateRequest.Size(m)
}
func (m *EventCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventCreateRequest proto.InternalMessageInfo

func (m *EventCreateRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type EventCreateResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventCreateResponse) Reset()         { *m = EventCreateResponse{} }
func (m *EventCreateResponse) String() string { return proto.CompactTextString(m) }
func (*EventCreateResponse) ProtoMessage()    {}
func (*EventCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_542299000a857ba7, []int{2}
}

func (m *EventCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventCreateResponse.Unmarshal(m, b)
}
func (m *EventCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventCreateResponse.Marshal(b, m, deterministic)
}
func (m *EventCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventCreateResponse.Merge(m, src)
}
func (m *EventCreateResponse) XXX_Size() int {
	return xxx_messageInfo_EventCreateResponse.Size(m)
}
func (m *EventCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventCreateResponse proto.InternalMessageInfo

func (m *EventCreateResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type EventUpdateRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventUpdateRequest) Reset()         { *m = EventUpdateRequest{} }
func (m *EventUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*EventUpdateRequest) ProtoMessage()    {}
func (*EventUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_542299000a857ba7, []int{3}
}

func (m *EventUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventUpdateRequest.Unmarshal(m, b)
}
func (m *EventUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventUpdateRequest.Marshal(b, m, deterministic)
}
func (m *EventUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUpdateRequest.Merge(m, src)
}
func (m *EventUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_EventUpdateRequest.Size(m)
}
func (m *EventUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventUpdateRequest proto.InternalMessageInfo

func (m *EventUpdateRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type EventUpdateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventUpdateResponse) Reset()         { *m = EventUpdateResponse{} }
func (m *EventUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*EventUpdateResponse) ProtoMessage()    {}
func (*EventUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_542299000a857ba7, []int{4}
}

func (m *EventUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventUpdateResponse.Unmarshal(m, b)
}
func (m *EventUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventUpdateResponse.Marshal(b, m, deterministic)
}
func (m *EventUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUpdateResponse.Merge(m, src)
}
func (m *EventUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_EventUpdateResponse.Size(m)
}
func (m *EventUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventUpdateResponse proto.InternalMessageInfo

func (m *EventUpdateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EventDeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDeleteRequest) Reset()         { *m = EventDeleteRequest{} }
func (m *EventDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*EventDeleteRequest) ProtoMessage()    {}
func (*EventDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_542299000a857ba7, []int{5}
}

func (m *EventDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDeleteRequest.Unmarshal(m, b)
}
func (m *EventDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDeleteRequest.Marshal(b, m, deterministic)
}
func (m *EventDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDeleteRequest.Merge(m, src)
}
func (m *EventDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_EventDeleteRequest.Size(m)
}
func (m *EventDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventDeleteRequest proto.InternalMessageInfo

func (m *EventDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type EventDeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventDeleteResponse) Reset()         { *m = EventDeleteResponse{} }
func (m *EventDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*EventDeleteResponse) ProtoMessage()    {}
func (*EventDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_542299000a857ba7, []int{6}
}

func (m *EventDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDeleteResponse.Unmarshal(m, b)
}
func (m *EventDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDeleteResponse.Marshal(b, m, deterministic)
}
func (m *EventDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDeleteResponse.Merge(m, src)
}
func (m *EventDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_EventDeleteResponse.Size(m)
}
func (m *EventDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventDeleteResponse proto.InternalMessageInfo

func (m *EventDeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EventListRequest struct {
	Period               Period   `protobuf:"varint,1,opt,name=period,proto3,enum=entities.Period" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventListRequest) Reset()         { *m = EventListRequest{} }
func (m *EventListRequest) String() string { return proto.CompactTextString(m) }
func (*EventListRequest) ProtoMessage()    {}
func (*EventListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_542299000a857ba7, []int{7}
}

func (m *EventListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventListRequest.Unmarshal(m, b)
}
func (m *EventListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventListRequest.Marshal(b, m, deterministic)
}
func (m *EventListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventListRequest.Merge(m, src)
}
func (m *EventListRequest) XXX_Size() int {
	return xxx_messageInfo_EventListRequest.Size(m)
}
func (m *EventListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventListRequest proto.InternalMessageInfo

func (m *EventListRequest) GetPeriod() Period {
	if m != nil {
		return m.Period
	}
	return Period_ALL
}

type EventListResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventListResponse) Reset()         { *m = EventListResponse{} }
func (m *EventListResponse) String() string { return proto.CompactTextString(m) }
func (*EventListResponse) ProtoMessage()    {}
func (*EventListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_542299000a857ba7, []int{8}
}

func (m *EventListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventListResponse.Unmarshal(m, b)
}
func (m *EventListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventListResponse.Marshal(b, m, deterministic)
}
func (m *EventListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventListResponse.Merge(m, src)
}
func (m *EventListResponse) XXX_Size() int {
	return xxx_messageInfo_EventListResponse.Size(m)
}
func (m *EventListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventListResponse proto.InternalMessageInfo

func (m *EventListResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func init() {
	proto.RegisterEnum("entities.Period", Period_name, Period_value)
	proto.RegisterType((*Event)(nil), "entities.Event")
	proto.RegisterType((*EventCreateRequest)(nil), "entities.EventCreateRequest")
	proto.RegisterType((*EventCreateResponse)(nil), "entities.EventCreateResponse")
	proto.RegisterType((*EventUpdateRequest)(nil), "entities.EventUpdateRequest")
	proto.RegisterType((*EventUpdateResponse)(nil), "entities.EventUpdateResponse")
	proto.RegisterType((*EventDeleteRequest)(nil), "entities.EventDeleteRequest")
	proto.RegisterType((*EventDeleteResponse)(nil), "entities.EventDeleteResponse")
	proto.RegisterType((*EventListRequest)(nil), "entities.EventListRequest")
	proto.RegisterType((*EventListResponse)(nil), "entities.EventListResponse")
}

func init() {
	proto.RegisterFile("api/internal/domain/entities/Event.proto", fileDescriptor_542299000a857ba7)
}

var fileDescriptor_542299000a857ba7 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x26, 0xe9, 0xd2, 0xa6, 0x27, 0x68, 0x04, 0xc3, 0x45, 0x08, 0x20, 0xaa, 0x88, 0x49, 0x15,
	0x17, 0xc9, 0x54, 0x24, 0x2e, 0xd8, 0x6e, 0x06, 0x2b, 0x82, 0x52, 0x7e, 0x14, 0x86, 0x10, 0xdc,
	0x4c, 0x59, 0x73, 0x36, 0x59, 0x6a, 0xed, 0x60, 0xbb, 0x43, 0x3c, 0x06, 0xaf, 0xc3, 0xd3, 0xa1,
	0xda, 0x71, 0xd7, 0x66, 0x45, 0xdb, 0xee, 0xe2, 0x73, 0xbe, 0x9f, 0x93, 0xf3, 0xc5, 0x81, 0x7e,
	0x51, 0xd1, 0x8c, 0x32, 0x85, 0x82, 0x15, 0xd3, 0xac, 0xe4, 0xb3, 0x82, 0xb2, 0x0c, 0x99, 0xa2,
	0x8a, 0xa2, 0xcc, 0x86, 0xe7, 0xc8, 0x54, 0x5a, 0x09, 0xae, 0x38, 0xf1, 0x6d, 0x35, 0x7e, 0x72,
	0xc6, 0xf9, 0xd9, 0x14, 0x33, 0x5d, 0x3f, 0x99, 0x9f, 0x66, 0x8a, 0xce, 0x50, 0xaa, 0x62, 0x56,
	0x19, 0x68, 0xf2, 0xc7, 0x05, 0x4f, 0x53, 0xc9, 0x36, 0xb8, 0xb4, 0x8c, 0x9c, 0x9e, 0xd3, 0xef,
	0xe6, 0x2e, 0x2d, 0xc9, 0x7d, 0xf0, 0x14, 0x55, 0x53, 0x8c, 0x5c, 0x5d, 0x32, 0x07, 0xd2, 0x83,
	0xa0, 0x44, 0x39, 0x11, 0xb4, 0x52, 0x94, 0xb3, 0xa8, 0xa5, 0x7b, 0xab, 0x25, 0xf2, 0x00, 0x7c,
	0xfe, 0x8b, 0xa1, 0x38, 0xa6, 0x65, 0xb4, 0xa5, 0xdb, 0x1d, 0x7d, 0x7e, 0x57, 0x92, 0x5d, 0xf0,
	0xa4, 0x2a, 0x84, 0x8a, 0xbc, 0x9e, 0xd3, 0x0f, 0x06, 0x71, 0x6a, 0xa6, 0x4b, 0xed, 0x74, 0xe9,
	0x91, 0x9d, 0x2e, 0x37, 0x40, 0xf2, 0x02, 0xfc, 0x72, 0x2e, 0x0a, 0xed, 0xd5, 0xbe, 0x92, 0xb4,
	0xc4, 0x92, 0x3d, 0x08, 0x18, 0x57, 0xf4, 0xf4, 0xf7, 0xf1, 0xe2, 0x85, 0xa3, 0xce, 0x95, 0x54,
	0x30, 0xf0, 0x45, 0x21, 0xd9, 0x03, 0xa2, 0x57, 0xf2, 0x5a, 0x60, 0xa1, 0x30, 0xc7, 0x9f, 0x73,
	0x94, 0x8a, 0xec, 0x80, 0x87, 0x8b, 0xaa, 0x5e, 0x51, 0x30, 0xb8, 0x93, 0xda, 0x25, 0xa7, 0x1a,
	0x9c, 0x9b, 0x6e, 0xb2, 0x0f, 0xf7, 0xd6, 0xc8, 0xb2, 0xe2, 0x4c, 0xe2, 0x75, 0xd9, 0xd6, 0xfa,
	0x6b, 0x55, 0xde, 0xdc, 0x7a, 0xa7, 0xb6, 0xb6, 0xe4, 0xda, 0xba, 0x11, 0x6c, 0xf2, 0xb4, 0xf6,
	0x38, 0xc4, 0x29, 0x5e, 0x78, 0x34, 0x51, 0x59, 0x2d, 0x66, 0x51, 0xb5, 0x58, 0x04, 0x1d, 0x39,
	0x9f, 0x4c, 0x50, 0x4a, 0x8d, 0xf5, 0x73, 0x7b, 0x4c, 0xf6, 0x21, 0xd4, 0x84, 0x31, 0x95, 0xca,
	0x8a, 0xf6, 0xa1, 0x5d, 0xa1, 0xa0, 0xdc, 0x08, 0x6f, 0x0f, 0xc2, 0x8b, 0xc9, 0x3f, 0xeb, 0x7a,
	0x5e, 0xf7, 0x93, 0x97, 0x70, 0x77, 0x85, 0x7d, 0xa3, 0xa5, 0x3d, 0xcb, 0xa0, 0x6d, 0xd4, 0x48,
	0x07, 0x5a, 0x07, 0xe3, 0x71, 0x78, 0x6b, 0xf1, 0x70, 0x78, 0xf0, 0x3d, 0x74, 0x88, 0x0f, 0x5b,
	0xdf, 0x86, 0xc3, 0xf7, 0xa1, 0x4b, 0xba, 0xe0, 0x7d, 0xf8, 0xf4, 0xf1, 0xe8, 0x6d, 0xd8, 0x1a,
	0xfc, 0x75, 0xe1, 0xb6, 0x56, 0xf8, 0x82, 0xe2, 0x9c, 0x4e, 0x90, 0x8c, 0x20, 0x30, 0x79, 0x99,
	0xab, 0xf0, 0xa8, 0x61, 0xb4, 0xf6, 0x21, 0xc4, 0x8f, 0xff, 0xd3, 0xad, 0x87, 0x1e, 0x41, 0x60,
	0x02, 0xd8, 0xac, 0xb5, 0x96, 0xec, 0x25, 0xad, 0x46, 0x74, 0x23, 0x08, 0xcc, 0xfe, 0x37, 0x6b,
	0xad, 0x25, 0x78, 0x49, 0xab, 0x91, 0xdc, 0x1b, 0xe8, 0x2e, 0x37, 0x4c, 0xe2, 0x06, 0x76, 0x25,
	0xb4, 0xf8, 0xe1, 0xc6, 0x9e, 0x51, 0xd9, 0x75, 0x5e, 0xc1, 0x8f, 0xe5, 0xef, 0xe5, 0xa4, 0xad,
	0x6f, 0xd2, 0xf3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xec, 0x92, 0xc5, 0x9b, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	CreateEvent(ctx context.Context, in *EventCreateRequest, opts ...grpc.CallOption) (*EventCreateResponse, error)
	UpdateEvent(ctx context.Context, in *EventUpdateRequest, opts ...grpc.CallOption) (*EventUpdateResponse, error)
	DeleteEvent(ctx context.Context, in *EventDeleteRequest, opts ...grpc.CallOption) (*EventDeleteResponse, error)
	EventList(ctx context.Context, in *EventListRequest, opts ...grpc.CallOption) (EventService_EventListClient, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *EventCreateRequest, opts ...grpc.CallOption) (*EventCreateResponse, error) {
	out := new(EventCreateResponse)
	err := c.cc.Invoke(ctx, "/entities.EventService/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateEvent(ctx context.Context, in *EventUpdateRequest, opts ...grpc.CallOption) (*EventUpdateResponse, error) {
	out := new(EventUpdateResponse)
	err := c.cc.Invoke(ctx, "/entities.EventService/UpdateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteEvent(ctx context.Context, in *EventDeleteRequest, opts ...grpc.CallOption) (*EventDeleteResponse, error) {
	out := new(EventDeleteResponse)
	err := c.cc.Invoke(ctx, "/entities.EventService/DeleteEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) EventList(ctx context.Context, in *EventListRequest, opts ...grpc.CallOption) (EventService_EventListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EventService_serviceDesc.Streams[0], "/entities.EventService/EventList", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventServiceEventListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventService_EventListClient interface {
	Recv() (*EventListResponse, error)
	grpc.ClientStream
}

type eventServiceEventListClient struct {
	grpc.ClientStream
}

func (x *eventServiceEventListClient) Recv() (*EventListResponse, error) {
	m := new(EventListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	CreateEvent(context.Context, *EventCreateRequest) (*EventCreateResponse, error)
	UpdateEvent(context.Context, *EventUpdateRequest) (*EventUpdateResponse, error)
	DeleteEvent(context.Context, *EventDeleteRequest) (*EventDeleteResponse, error)
	EventList(*EventListRequest, EventService_EventListServer) error
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) CreateEvent(ctx context.Context, req *EventCreateRequest) (*EventCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}
func (*UnimplementedEventServiceServer) UpdateEvent(ctx context.Context, req *EventUpdateRequest) (*EventUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (*UnimplementedEventServiceServer) DeleteEvent(ctx context.Context, req *EventDeleteRequest) (*EventDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (*UnimplementedEventServiceServer) EventList(req *EventListRequest, srv EventService_EventListServer) error {
	return status.Errorf(codes.Unimplemented, "method EventList not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.EventService/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*EventCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.EventService/UpdateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateEvent(ctx, req.(*EventUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entities.EventService/DeleteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteEvent(ctx, req.(*EventDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_EventList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventServiceServer).EventList(m, &eventServiceEventListServer{stream})
}

type EventService_EventListServer interface {
	Send(*EventListResponse) error
	grpc.ServerStream
}

type eventServiceEventListServer struct {
	grpc.ServerStream
}

func (x *eventServiceEventListServer) Send(m *EventListResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "entities.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventService_DeleteEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventList",
			Handler:       _EventService_EventList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/internal/domain/entities/Event.proto",
}
